### ISSUE TITLE
How INSERT UNIQUE VALUES?

### ISSUE THREAD

**Issue by IProudNoob** [agershun/alasql#1202]
Hi! 
I try I try and create this example:

```
var alasql = require('alasql');
var db = new alasql.Database();

db.exec("CREATE TABLE job (user STRING UNIQUE)");

db.exec("INSERT INTO job VALUES ('Bob')");
db.exec("INSERT INTO job VALUES ('Tom')");
db.exec("INSERT INTO job VALUES ('Jon')");
db.exec("INSERT INTO job VALUES ('Jon')");

var res = db.exec("SELECT * FROM job ORDER BY b DESC");

console.log(res)
```
But in console I see error:
```

PS D:\SQL\v1> node .\index.js
D:\SQL\v1\node_modules\alasql\dist\alasql.fs.js:13135
                                        else throw new Error('Cannot insert record, because it already exists in unique index');
                                             ^
Error: Cannot insert record, because it already exists in unique index
    at D:\SQL\v1\node_modules\alasql\dist\alasql.fs.js:13135:17
    at Array.forEach (<anonymous>)
    at alasql.Table.table.insert (D:\SQL\v1\node_modules\alasql\dist\alasql.fs.js:13131:13)
    at yy.Insert.eval (eval at yy.Insert.compile (D:\SQL\v1\node_modules\alasql\dist\alasql.fs.js:14764:18), <anonymous>:1:114)
    at statement (D:\SQL\v1\node_modules\alasql\dist\alasql.fs.js:14828:14)
    at Function.alasql.dexec (D:\SQL\v1\node_modules\alasql\dist\alasql.fs.js:4640:11)
    at alasql.Database.Database.exec (D:\SQL\v1\node_modules\alasql\dist\alasql.fs.js:5385:16)
    at Object.<anonymous> (D:\SQL\v1\index.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
```

How to fix it?

THX :)

**Comment by mathiasrw** [comment]
You are inserting "Jon" twice. As yuo asked to make the string `unique` it throws an error.
