### ISSUE TITLE
select if

### ISSUE THREAD

**Issue by pasapsi** [agershun/alasql#340]
Is it possible to do if in select

Sample

```
mysql> SELECT IF(1>2,2,3);
        -> 3
```

**Comment by mathiasrw** [comment]
No its not supported at the moment

```
alacon "select if(1>2,2,3)"                                                                                                                                                                                
                                                                                                                                                                                                                                                                            
/home/action/.parts/lib/node_modules/alasql/dist/alasql.js:1797                                                                                                                                                                                                             
        throw new Error(str);                                                                                                                                                                                                                                               
              ^                                                                                                                                                                                                                                                             
Error: Parse error on line 1:                                                                                                                                                                                                                                               
select if(1>2,2,3)                                                                                                                                                                                                                                                          
-------^                                                                                                                                                                                                                                                                    
Expecting 'LITERAL', 'BRALITERAL', 'EOF', 'WITH', 'LPAR', 'RPAR', 'REMOVE', 'ORDER', 'WHERE', 'NUMBER', 'STRING', 'SHARP', 'DOLLAR', 'AT', 'VALUE', 'ROW', 'COLON', 'NOT', 'UNION', 'ALL', 'INTERSECT', 'EXCEPT', 'PLUS', 'STAR', 'QUESTION', 'FROM', 'DISTINCT', 'UNIQUE', 
'COLUMN', 'MATRIX', 'TEXTSTRING', 'INDEX', 'RECORDSET', 'TOP', 'INTO', 'GROUP', 'LIMIT', 'CURRENT_TIMESTAMP', 'JAVASCRIPT', 'NEW', 'CAST', 'CONVERT', 'SUM', 'COUNT', 'MIN', 'MAX', 'AVG', 'FIRST', 'LAST', 'AGGR', 'ARRAY', 'TRUE', 'FALSE', 'NSTRING', 'NULL', 'EXISTS', '
BRAQUESTION', 'CASE', 'END', 'ELSE', 'MINUS', 'ATLBRA', 'LCUR', 'SEMICOLON', 'GO', got 'IF'                                                                                                                                                                                 
    at Object.parseError (/home/action/.parts/lib/node_modules/alasql/dist/alasql.js:1797:15)                                                                                                                                                                               
    at Object.parse (/home/action/.parts/lib/node_modules/alasql/dist/alasql.js:1862:22)                                                                                                                                                                                    
    at Function.alasql.parse (/home/action/.parts/lib/node_modules/alasql/dist/alasql.js:3903:16)                                                                                                                                                                           
    at Function.alasql.dexec (/home/action/.parts/lib/node_modules/alasql/dist/alasql.js:4051:19)                                                                                                                                                                           
    at Function.alasql.exec (/home/action/.parts/lib/node_modules/alasql/dist/alasql.js:4028:17)                                                                                                                                                                            
    at alasql (/home/action/.parts/lib/node_modules/alasql/dist/alasql.js:120:18)                                                                                                                                                                                           
    at Object.<anonymous> (/home/action/.parts/lib/node_modules/alasql/bin/alacon.js:42:12)                                                                                                                                                                                 
    at Module._compile (module.js:456:26)                                                                                                                                                                                                                                   
    at Object.Module._extensions..js (module.js:474:10)                                                                                                                                                                                                                     
    at Module.load (module.js:356:32)                               
```

@agershun can you find a good spot on the roadmap to this?

**Comment by agershun** [comment]
Please, ise ```IIF()``` function:
```
    SELECT IIF(1>2,2,3)
```

**Comment by mathiasrw** [comment]
Interesting... `IIF`... did not know that. 

What is the reason we have not implemented it as `IF` ?

**Comment by agershun** [comment]
1. There is such function in MS SQL Server function (https://msdn.microsoft.com/en-us/library/hh213574.aspx)
2. ```IF``` is a reserved keyword, and we need to write a special grammar rule in this case.

**Comment by mathiasrw** [comment]
Makes sense. 

I have a feeling that with our Compatibility flags we should work towards a  solution where we can handle both.

**Comment by agershun** [comment]
I can add a special grammar rule for ```IF()``` function.

**Comment by mathiasrw** [comment]
:+1:

**Comment by mathiasrw** [comment]
Zap!!!!! Love the bug hunting speed !

**Comment by mathiasrw** [comment]
Can see changes nor test363.js in development branch. did you remember to push?

You might have to pull and see if any conflicts emerged and push your changes...

**Comment by agershun** [comment]
it was pushed already https://github.com/agershun/alasql/commit/a9454d70221222a8d0c8c5ffae7db4cfa093449e

**Comment by mathiasrw** [comment]
Ahhh, i get it. Sorry i did not check. You pusher directly to Master.

 I make sure the changes gets into dev.

**Comment by agershun** [comment]
No, I pushed it only to ```develop```, not to ```master```.

**Comment by mathiasrw** [comment]
Wow - I must stop looking at github from my phone. 

Sorry for all the confusion. Its all as it should be...

**Comment by agershun** [comment]
I just check, CodeHub for iPhone also does not show the updated branch.

**Comment by mathiasrw** [comment]
Makes so much more sense - I also use Codehub on the phone...
