### ISSUE TITLE
Table alias not able to parse

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#357]
When I run

    alasql.compile("SELECT * FROM Table_A A LEFT JOIN Table_B B ON A.Key = B.Key WHERE B.Key IS NULL");

I get the following error

```
alasql.js:1818 Uncaught Error: Parse error on line 1:
...JOIN Table_B B ON A.Key = B.Key WHERE B.
-----------------------^
Expecting 'LITERAL', 'BRALITERAL', 'VALUE', 'STAR', got 'KEY'
```

now - I had a feeling it was because of the name "key" but changing it just gave another error:

```
alasql.compile("SELECT * FROM Table_A A LEFT JOIN Table_B B ON A.abc = B.abc WHERE B.abc IS NULL");

alasql.js:9407 Uncaught TypeError: Cannot read property 'columns' of undefined
    at file:///Users/mrw/slet/kunstbibmerge/alasql.js:9407:13
    at Array.forEach (native)
    at yy.Select.compileDefCols (file:///Users/mrw/slet/kunstbibmerge/alasql.js:9398:13)
    at yy.Select.compile (file:///Users/mrw/slet/kunstbibmerge/alasql.js:7095:23)
    at Function.alasql.compile (file:///Users/mrw/slet/kunstbibmerge/alasql.js:4270:37)
    at <anonymous>:3:8
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

I have a feeling the alias of the table is not supported

(using the 0.1.10 version at development branch)

**Comment by mathiasrw** [comment]
Using 0.1.9 and taking the example from https://github.com/agershun/alasql/wiki/Join

```
alasql.compile('SELECT city.*, country.* FROM city \
                JOIN country ON city.countryid = country.countryid');

alasql.min.js:12 Uncaught TypeError: Cannot read property 'columns' of undefined
    at file:///Users/mrw/slet/kunstbibmerge/alasql.min.js:12:2251
    at Array.forEach (native)
    at yy.Select.compileDefCols (file:///Users/mrw/slet/kunstbibmerge/alasql.min.js:12:2094)
    at yy.Select.compile (file:///Users/mrw/slet/kunstbibmerge/alasql.min.js:11:324)
    at Function.alasql.compile (file:///Users/mrw/slet/kunstbibmerge/alasql.min.js:7:28509)
    at <anonymous>:2:8
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

**Comment by mathiasrw** [comment]
Using version 0.1.1 cant compile the example

alasql.compile('SELECT city.*, country.* FROM city \
                JOIN country ON city.countryid = country.countryid');

alasql.0.1.1.js:7744 Uncaught TypeError: Cannot read property 'columns' of undefined
    at file:///Users/mrw/slet/kunstbibmerge/alasql.0.1.1.js:7744:13
    at Array.forEach (native)
    at yy.Select.compileDefCols (file:///Users/mrw/slet/kunstbibmerge/alasql.0.1.1.js:7735:13)
    at yy.Select.compile (file:///Users/mrw/slet/kunstbibmerge/alasql.0.1.1.js:5677:23)
    at Function.alasql.compile (file:///Users/mrw/slet/kunstbibmerge/alasql.0.1.1.js:3670:28)
    at <anonymous>:2:8
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)

**Comment by mathiasrw** [comment]
Using version 0.0.40 still cant compile

```
alasql.compile('SELECT city.*, country.* FROM city \
                JOIN country ON city.countryid = country.countryid');

alasql-0.0.40.js:6703 Uncaught TypeError: Cannot read property 'columns' of undefined
    at file:///Users/mrw/slet/kunstbibmerge/alasql-0.0.40.js:6703:13
    at Array.forEach (native)
    at yy.Select.compileDefCols (file:///Users/mrw/slet/kunstbibmerge/alasql-0.0.40.js:6694:13)
    at yy.Select.compile (file:///Users/mrw/slet/kunstbibmerge/alasql-0.0.40.js:4841:23)
    at Function.alasql.compile (file:///Users/mrw/slet/kunstbibmerge/alasql-0.0.40.js:3425:28)
    at <anonymous>:2:8
    at Object.InjectedScript._evaluateOn (<anonymous>:895:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:828:34)
    at Object.InjectedScript.evaluate (<anonymous>:694:21)
```

**Comment by agershun** [comment]
```KEY``` is a keyword for AlaSQL, so we need to put it in the brackets ```[Key]```.. Could you check this issue again?

**Comment by mathiasrw** [comment]
I have updated the readme with info about this: https://github.com/agershun/alasql#limitations

**Comment by luchojuarez** [comment]
@agershun I have the same problem, help me?
have a factory named "Player" & this is de save function.
error in line: alasql('UPDATE ticDB.players SET points = ? WHERE name = ?;',[toSave.points,toSave.name]);

complete code function: 
save:function (player) {
            alasql('CREATE localStorage DATABASE IF NOT EXISTS player;');
            alasql('ATTACH localStorage DATABASE player AS ticDB;');
           var toSave = alasql('SELECT * FROM ticDB.players where name=?;',[player.name])[0];
            toSave.points+=player.points;
            alasql('UPDATE ticDB.players SET points = ? WHERE name = ?;',[toSave.points,toSave.name]);
            alasql('DETACH DATABASE ticDB');
        },

**Comment by mathiasrw** [comment]
You are missing a `,` between  `...WHERE name = ?;'` and  `[toSave.points,toSave.name]...`
