### ISSUE TITLE
INTO XLSXML -> INTO XLSX

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#377]
It seams to greate confusion that you 

* `SELECT INTO CSV` for `.csv` files
* `SELECT INTO XSL` for `.xsl` files

but 

* `SELECT INTO XSLXML` for `.xslx` files

I suggest we rename it so we use 

* `SELECT INTO XSLX` for `.xslx` files

**Comment by mathiasrw** [comment]
Have been playing with the XSLX and XSLXML realizing its 2 different things. 

I suggest that we implement that if xslx.core is not present we display meaningful error message in the console instead of the error thrown at the moment. 

```
TypeError: Cannot read property 'write' of undefined
    at saveWorkbook (http://alasql.org/console/alasql.min.js:9:15277)
    at doExport (http://alasql.org/console/alasql.min.js:9:13590)
    at Object.alasql.into.XLSX (http://alasql.org/console/alasql.min.js:9:13337)
```
