### ISSUE TITLE
Cannot read property 'write' of undefined

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#384]
I suggest if xslx.core is not present when `SELECT INTO XSLX()` is called we display a more meaningful error message in the console instead of:

```js
TypeError: Cannot read property 'write' of undefined
    at saveWorkbook (http://alasql.org/console/alasql.min.js:9:15277)
    at doExport (http://alasql.org/console/alasql.min.js:9:13590)
    at Object.alasql.into.XLSX (http://alasql.org/console/alasql.min.js:9:13337)
```

**Comment by johnmichaelrivera** [comment]
Hi!! I've got the same issue there...

I'm using SELECT INTO XLSX()
Do you know the solution?Thanks

TypeError: Cannot read property 'write' of undefined
    at saveWorkbook (http://localhost/start/dashboard/js/libraries/alasql.min.js:10:11230)
    at doExport (http://localhost/start/dashboard/js/libraries/alasql.min.js:10:9543)
    at Object.alasql.into.XLSX (http://localhost/start/dashboard/js/libraries/alasql.min.js:10:9290)
    at eval [as intoallfn] (eval at <anonymous> (http://localhost/start/dashboard/js/libraries/alasql.min.js:6:8390), <anonymous>:3:33)
    at queryfn3 (http://localhost/start/dashboard/js/libraries/alasql.min.js:5:28698)
    at queryfn2 (http://localhost/start/dashboard/js/libraries/alasql.min.js:5:24797)
    at Object.eval [as datafn] (eval at <anonymous> (http://localhost/start/dashboard/js/libraries/alasql.min.js:6:14596), <anonymous>:3:57)
    at http://localhost/start/dashboard/js/libraries/alasql.min.js:5:24144
    at Array.forEach (native)
    at queryfn (http://localhost/start/dashboard/js/libraries/alasql.min.js:5:24082)

**Comment by mathiasrw** [comment]
you need to include xlsx.js 

http://alasql.org/console/xlsx.core.min.js

**Comment by johnmichaelrivera** [comment]
Thanks!!!
Now I can download it as excel file but no data displaying. I console the result and it returns (an empty string)

**Comment by mathiasrw** [comment]
It gets more easy to help you if you provide example code

**Comment by johnmichaelrivera** [comment]
Can you help me about my problem?
I want to export the table as excel wherein i just need to export three fields.
The two fields are fixed data from table and One fields is from databse.


For my html table codes:
<table>
<thead>
    <h1>Monthly Cut off</h1>
    <th>FROM</th>
    <th><font color="#fff">space space space</font></th>
    <th>TO</th>
   
</thead>    
<tbody>
<tr>
    <td><h2>{{from |date:'MM-dd-yyyy'}}</h2></td>

    <center><td><h2><font color="#fff">-</font></h2></td></center>

    <td><h2>{{to |date:'MM-dd-yyyy'}}</h2></td>
    </tr>  
    </tbody>
    
    </table>
</center>
<br />
<div class="row">
    <div class="col-lg-12">
    <div class="table-responsive">
            <table class="table table-hover table-striped table-condensed">
             
                
                <thead>
                    <th>Employee's Name</th>
                    <th>CashCard</th>
                    <th>E-Money Card Account#</th>
                    <th>Salary</th>

                    
                </thead>
                <tbody>

                    <tr dir-paginate="item in CompanyList | itemsPerPage: 9 | filter:searchText" pagination-id="companylist">
                        <td>{{item.fullname}}</td>
                        <td ng-model="item.cashcard">0037</td>
                        <td>{{item.ecardacctno}}</td>
                        <td><input ng-model="item.salary" type="text" placeholder="Amount" style="width:100px"/></td>

                    </tr>
                    <tr ng-if="isNull && !isLoading">
                        <td colspan="4">No Data</td>
                    </tr>
                    <tr ng-if="isNull && isLoading">
                        <td colspan="4" class="text-center"><i class="fa fa-spinner fa-spin"></i></td>
                    </tr>
                </tbody>
            </table>
            {{CompanyList}}
        </div>


JS controller:

  $scope.ExportToExcel = function(keyword){
        
		if($scope.CompanyList.length > 0){
			$scope.exportLoading = true;
			toastr.info('Generating report, this might take a while. Thank you for your patience!');
			var filename = "Payroll_Transactions_"+GetCurrentDate()+".xlsx";
			CompanyFactory.ExportAll().success(function(result){
				//export
                console.log(result);
                
              
                //Export only e money card account number and the data in UI following fields: CashCard and salary and compute with total amount  //
                if(!keyword){
                    var a = alasql("SELECT [ecardacctno] INTO XLSX('"+filename+"', {headers:false}) FROM ? ORDER BY lname ASC", [result]);        
                    console.log(result);
                }else{
                    var a = alasql('SELECT [ecardacctno] AS ACCOUNTNUMBER INTO XLSX("'+filename+'", {headers:false}) FROM ? WHERE [lname] = "'+keyword+'" ORDER BY LASTNAME ASC', [result]);
                }
				
				if(a == 1){
					$scope.exportLoading = false;
					toastr.success('Data exported!');
					angular.element('#excelModal').modal('hide');
				}else{
					$scope.exportLoading = false;
					toastr.error('Error exporting data.');
				}
			})	
		}else{
			toastr.warning('Please wait while the application is loading the records.');
		}
		
	}

**Comment by johnmichaelrivera** [comment]
As you can see the fixed data in my table is the cashcard field, the salary field which is blank,i will input some amount there and i'd like to export it to excel.The fields i'm going to export only are cashcard,E-money account and salary thanks

**Comment by mathiasrw** [comment]
so - you have a table with many fields, but you only want to work with a few of them - is that correct?

**Comment by johnmichaelrivera** [comment]
Thanks.. I've done working on it my only problem now is on my js.
I have two queries.Whenever i export to excel it only displaying "[object] [object]"


 $scope.ExportToExcel = function(){
   
		if($scope.CompanyList.length > 0){
			$scope.exportLoading = true;
			toastr.info('Generating report, this might take a while. Thank you for your patience!');
			var filename = "Payroll_Transactions_"+GetCurrentDate()+".xlsx";
            
  
            var cc = alasql("SELECT [cashcardnumber] AS cashcard FROM ? WHERE company_id = ?",[$scope.CorporateList]);
            console.log(cc);
            
            
            var ec = alasql("SELECT [emoneycard] AS ecardacctno FROM ? WHERE company_id = ?",[$scope.CorporateList]);
            console.log(ec);
            
            var a1 = [{"rowcount":"BF", "cashcard":[cc], "ecardacctno":[ec], "salary":""}];
                
                var a = alasql("SELECT ROWNUM() AS [rowcount], [cashcard], [ecardacctno], [salary] FROM ? ORDER BY lname ASC", [$scope.CompanyList]);
            
                var b = alasql("SELECT SUM(salary) AS [salary] FROM ?", [a]);
			    var total = {"rowcount":"BR", "cashcard":"", "ecardacctno":"", "salary":""};    
                total.salary = b[0].salary;
                
            for(var i = 0 ; i <= a.length-1 ; i++){
                a[i].rowcount = "0" + a[i].rowcount;
                a1.push(a[i]);
            }
                a1.push(total);
//                console.log(a1);
         
                var c = alasql("SELECT [rowcount], [cashcard], [ecardacctno], [salary] INTO XLSX('"+filename+"', {headers:false}) FROM ?", [a1]);
            

				if(c == 1){
					$scope.exportLoading = false;
					toastr.success('Data exported!');
					angular.element('#excelModal').modal('hide');
				}else{
					$scope.exportLoading = false;
					toastr.error('Error exporting data.');
                }
        }else{
			toastr.warning('Please wait while the application is loading the records.');
		}
		
	
    }

This is my script

**Comment by mathiasrw** [comment]
@johnmichaelrivera Any news on this?

**Comment by mathiasrw** [comment]
@johnmichaelrivera Any news on this?

**Comment by mathiasrw** [comment]
Closing due to inactivity. Please reopen if needed.
