### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by mathiasrw** [agershun/alasql#476]
In
https://github.com/agershun/alasql/blob/324a8c07ee5739477779e7bae222f3f9ef17ee21/test/test092.js
It looks like the we are missing tests for 

```sql
TRUNC
CHAR
CONCAT
CONCAT_WS
LEFT
LPAD
SUBSTR
SUBSTRING
TRIM
COALESCE
VALUE
```

I make the issue here to remember to implement them

**Update:**

The following have beem removed from the first list because tests have been implemented

```sql
CEIL
FLOOR
ROUND
ASCII
```

**Comment by mathiasrw** [comment]
Input for test cases:

```sql

----

SELECT(CEIL(17.36)) 
  18

SELECT CEIL(-17.36) 
    -17

----

-- MSSQL
SELECT CEILING(12.9273);
13

SELECT FLOOR(12.9273);
12    


---- 
-- https://www.mssqltips.com/sqlservertip/1589/sql-server-rounding-functions--round-ceiling-and-floor/

DECLARE @value int
SET @value = 6

SELECT ROUND(@value, 1)  -- 6 - No rounding with no digits right of the decimal point
SELECT CEILING(@value)   -- 6 - Smallest integer value
SELECT FLOOR(@value)     -- 6 - Largest integer value 




DECLARE @value int
SET @value = 6

SELECT ROUND(@value, 1)  -- 6  - No rounding with no digits right of the decimal point
SELECT ROUND(@value, -1) -- 10 - Rounding up with digits on the left of the decimal point
SELECT ROUND(@value, 2)  -- 6  - No rounding with no digits right of the decimal point 
SELECT ROUND(@value, -2) -- 0  - Insufficient number of digits
SELECT ROUND(@value, 3)  -- 6  - No rounding with no digits right of the decimal point
SELECT ROUND(@value, -3) -- 0  - Insufficient number of digits






SELECT ROUND(444,  1) -- 444  - No rounding with no digits right of the decimal point
SELECT ROUND(444, -1) -- 440  - Rounding down
SELECT ROUND(444,  2) -- 444  - No rounding with no digits right of the decimal point
SELECT ROUND(444, -2) -- 400  - Rounding down
SELECT ROUND(444,  3) -- 444  - No rounding with no digits right of the decimal point
SELECT ROUND(444, -3) -- 0    - Insufficient number of digits
SELECT ROUND(444,  4) -- 444  - No rounding with no digits right of the decimal point
SELECT ROUND(444, -4) -- 0    - Insufficient number of digits

SELECT ROUND(555,  1) -- 555  - No rounding with no digits right of the decimal point
SELECT ROUND(555, -1) -- 560  - Rounding up
SELECT ROUND(555,  2) -- 555  - No rounding with no digits right of the decimal point
SELECT ROUND(555, -2) -- 600  - Rounding up
SELECT ROUND(555,  3) -- 555  - No rounding with no digits right of the decimal point
SELECT ROUND(555, -3) -- 1000 - Rounding up
SELECT ROUND(555,  4) -- 555  - No rounding with no digits right of the decimal point
SELECT ROUND(555, -4) -- 0    - Insufficient number of digits

SELECT ROUND(666,  1) -- 666  - No rounding with no digits right of the decimal point
SELECT ROUND(666, -1) -- 670  - Rounding up
SELECT ROUND(666,  2) -- 666  - No rounding with no digits right of the decimal point
SELECT ROUND(666, -2) -- 700  - Rounding up
SELECT ROUND(666,  3) -- 666  - No rounding with no digits right of the decimal point
SELECT ROUND(666, -3) -- 1000 - Rounding up
SELECT ROUND(666,  4) -- 666  - No rounding with no digits right of the decimal point
SELECT ROUND(666, -4) -- 0    - Insufficient number of digits



SELECT ROUND(-444, -1) -- -440  - Rounding down
SELECT ROUND(-444, -2) -- -400  - Rounding down

SELECT ROUND(-555, -1) -- -560  - Rounding up
SELECT ROUND(-555, -2) -- -600  - Rounding up

SELECT ROUND(-666, -1) -- -670  - Rounding up
SELECT ROUND(-666, -2) -- -700  - Rounding up


DECLARE @value int
SET @value = 16.999999

SELECT ROUND(@value,  1) -- 16 - No rounding with no digits right of the decimal point i.e. int
SELECT ROUND(@value, -1) -- 20 - Round up
SELECT CEILING(@value)   -- 16 - Smallest integer value
SELECT FLOOR(@value)     -- 16 - Largest integer value 
SELECT @value            -- 16 - Shows how the @value is evaluated based on the int data type 





SET @value = 11.05

SELECT ROUND(@value, 1)  -- 11.10
SELECT ROUND(@value, -1) -- 10.00 

SELECT ROUND(@value, 2)  -- 11.05 
SELECT ROUND(@value, -2) -- 0.00 

SELECT ROUND(@value, 3)  -- 11.05
SELECT ROUND(@value, -3) -- 0.00

SELECT CEILING(@value)   -- 12 
SELECT FLOOR(@value)     -- 11 










DECLARE @value numeric(10,10)
SET @value = .5432167890
SELECT ROUND(@value, 1)  -- 0.5000000000 
SELECT ROUND(@value, 2)  -- 0.5400000000
SELECT ROUND(@value, 3)  -- 0.5430000000
SELECT ROUND(@value, 4)  -- 0.5432000000
SELECT ROUND(@value, 5)  -- 0.5432200000
SELECT ROUND(@value, 6)  -- 0.5432170000
SELECT ROUND(@value, 7)  -- 0.5432168000
SELECT ROUND(@value, 8)  -- 0.5432167900
SELECT ROUND(@value, 9)  -- 0.5432167890
SELECT ROUND(@value, 10) -- 0.5432167890
SELECT CEILING(@value)   -- 1
SELECT FLOOR(@value)     -- 0





DECLARE @value float(10)
SET @value = .1234567890
SELECT ROUND(@value, 1)  -- 0.1
SELECT ROUND(@value, 2)  -- 0.12
SELECT ROUND(@value, 3)  -- 0.123
SELECT ROUND(@value, 4)  -- 0.1235
SELECT ROUND(@value, 5)  -- 0.12346
SELECT ROUND(@value, 6)  -- 0.123457
SELECT ROUND(@value, 7)  -- 0.1234568
SELECT ROUND(@value, 8)  -- 0.12345679
SELECT ROUND(@value, 9)  -- 0.123456791
SELECT ROUND(@value, 10) -- 0.123456791
SELECT CEILING(@value)   -- 1
SELECT FLOOR(@value)     -- 0




```

**Comment by agershun** [comment]
@mathiasrw I just added [test374.js](https://github.com/agershun/alasql/blob/develop/test/test374.js)
I made minot changes in the test:
* replaced ```@value``` with ```@val``` due the known problem with this keyword
* added line ``` DECLARE @val float  ``` before the line with ```SET @value = 11.05``` (it should be defnitely not ```int``` type)

Something wrong with these lines in the test (no ```8``` in the results):
```
SELECT ROUND(@value, 9)  -- 0.123456791
SELECT ROUND(@value, 10) -- 0.123456791
```

Now we have only one problem in this test in the line:
```
SELECT ROUND(-555, -1) -- -560  - Rounding up  =>  but `AlaSQL gives -550
```
I think this is the error in the test result or in original function

**Comment by mathiasrw** [comment]
Great work with the test374. I have updated it a bit. I made a test for each statement so that we can see where the problem is if a test fails. 

I have made it so a line starting with `--` will be a skipped test. This way we can see in the test run that there is a test that we are skipping. To be able to run all tests including the skipped ones please run:

`mocha ./test/test374.js --forceall`

The `forceall` flag also works when running all tests - but please use:

`npm test -- --forceall`

(the extra `--` is an npm thing)

Another thing: I have made the results be compared as strings - and not as numbers. Not sure if this is clever. The thing is the `numeric` values where it expects trailing zeros (like `10.00`). As javascript does not support this om not sure if AlaSQL sould support traling zeros for, lets say a `DECIMAL 4,2` kind of value, converting it into a string before outputting it to make sure it has the correct number of traling zeros/calculates correctly

What do you say? Do we support trailing zeros?

In the moment we have the one error you mention and 14 others

```
  1) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(-555, -1) -- -560  - Rounding up:

      AssertionError: '-560' == '-550'
      + expected - actual

      --560
      +-550
      
      at Context.<anonymous> (test374.js:157:19)

  2) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 1)  -- 11.10:

      AssertionError: '11.10' == '11.1'
      + expected - actual

      -11.10
      +11.1
      
      at Context.<anonymous> (test374.js:157:19)

  3) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, -1) -- 10.00:

      AssertionError: '10.00' == '10'
      + expected - actual

      -10.00
      +10
      
      at Context.<anonymous> (test374.js:157:19)

  4) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, -2) -- 0.00:

      AssertionError: '0.00' == '0'
      + expected - actual

      -0.00
      +0
      
      at Context.<anonymous> (test374.js:157:19)

  5) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, -3) -- 0.00:

      AssertionError: '0.00' == '0'
      + expected - actual

      -0.00
      +0
      
      at Context.<anonymous> (test374.js:157:19)

  6) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 1)  -- 0.5000000000:

      AssertionError: '0.5000000000' == '0.5'
      + expected - actual

      -0.5000000000
      +0.5
      
      at Context.<anonymous> (test374.js:157:19)

  7) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 2)  -- 0.5400000000:

      AssertionError: '0.5400000000' == '0.54'
      + expected - actual

      -0.5400000000
      +0.54
      
      at Context.<anonymous> (test374.js:157:19)

  8) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 3)  -- 0.5430000000:

      AssertionError: '0.5430000000' == '0.543'
      + expected - actual

      -0.5430000000
      +0.543
      
      at Context.<anonymous> (test374.js:157:19)

  9) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 4)  -- 0.5432000000:

      AssertionError: '0.5432000000' == '0.5432'
      + expected - actual

      -0.5432000000
      +0.5432
      
      at Context.<anonymous> (test374.js:157:19)

  10) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 5)  -- 0.5432200000:

      AssertionError: '0.5432200000' == '0.54322'
      + expected - actual

      -0.5432200000
      +0.54322
      
      at Context.<anonymous> (test374.js:157:19)

  11) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 6)  -- 0.5432170000:

      AssertionError: '0.5432170000' == '0.543217'
      + expected - actual

      -0.5432170000
      +0.543217
      
      at Context.<anonymous> (test374.js:157:19)

  12) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 7)  -- 0.5432168000:

      AssertionError: '0.5432168000' == '0.5432168'
      + expected - actual

      -0.5432168000
      +0.5432168
      
      at Context.<anonymous> (test374.js:157:19)

  13) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 8)  -- 0.5432167900:

      AssertionError: '0.5432167900' == '0.54321679'
      + expected - actual

      -0.5432167900
      +0.54321679
      
      at Context.<anonymous> (test374.js:157:19)

  14) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 9)  -- 0.5432167890:

      AssertionError: '0.5432167890' == '0.543216789'
      + expected - actual

      -0.5432167890
      +0.543216789
      
      at Context.<anonymous> (test374.js:157:19)

  15) 374. CEILING, FLOOR, ROUND tests: SELECT ROUND(@val, 10) -- 0.5432167890:

      AssertionError: '0.5432167890' == '0.543216789'
      + expected - actual

      -0.5432167890
      +0.543216789
      
      at Context.<anonymous> (test374.js:157:19)


```

**Comment by mathiasrw** [comment]
I have created test376 and https://github.com/agershun/alasql/wiki/ASCII to explain what is going on. 

The library breaks when we `SELECT ASCII('\');` - I will create a new issue on that...

**Comment by agershun** [comment]
@mathiasrw Can we close this issue, beacuse we have separate for ```SELECT ASCII('\');``?

**Comment by mathiasrw** [comment]
Sure !
