### ISSUE TITLE
AlaSQL and Chakra

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#550]
Recently [Microsoft released Chakra](http://thenewstack.io/microsoft-chakra-javascript-engine-node/). How AlaSQL work with it?

**Comment by mathiasrw** [comment]
Interesting - lets keep an eye on it. I hope it gets will integrated into the node world so we dont have to test on yet another platform, but can set a flag for what engine we want. 

I looked at https://github.com/Microsoft/ChakraCore but looks like we need a Visual Studio to run it. I dont get why there is no "Download and try" button - I have asked in their gitter

**Comment by mathiasrw** [comment]
4 hours ago a pull request was made to the node.js repo to let node support a new engine. 

I will keep an eye on how things unfold.

**Comment by mathiasrw** [comment]
> It's important to remember that ChakraCore only currently builds on Windows, so this is only for Windows Node.js builds.
> The ChakraCore roadmap [1] shows that they plan on porting the interpreter to Ubuntu, but not to Mac OS, and they don't plan on porting the JIT. So even it does go Windows + Linux, it will still be a low-performing toy on Linux.
> This is vaguely interesting from a technical point of view, but doesn't seem like it'll majorly impact the future of Node.js, except maybe as something Microsoft can offer for Azure customers that choose Windows Server.

Lets wait and see how this turns out.

**Comment by mathiasrw** [comment]
The thing can be downloaded and installed from https://github.com/Microsoft/node/releases - only on windows now.

**Comment by agershun** [comment]
I worried about compatibility of modules and API. AlaSQL has a lot of internal calls to NodeJS standard modules (like ```fs```). Let we wait couple days, and I will install on my Windows computer.

**Comment by mathiasrw** [comment]
Hmm... as they are thinking the node-chakra integration the apps shuld not notice if node is using v8 or charkra as engine. 

So as long as we are running in a node/npm setup I think the focus of our worrienes should be if speed and correctness of the tests are still ok

**Comment by agershun** [comment]
Agree

**Comment by mathiasrw** [comment]
https://github.com/Microsoft/node/issues/10#issuecomment-173652057

**Comment by agershun** [comment]
:+1: Hard to understand where we call this --v8 flag...
What happen if you simply run ```mocha .```? The same result?

**Comment by mathiasrw** [comment]
We dont - its in the npm

**Comment by mathiasrw** [comment]
AlaSQL v0.2.2 `npm test` on chakra node v6.0.0-pre2:

```tap
  1323 passing (41s)
  57 pending
  20 failing

  1) Test 202 GETTIME and CAST 2. CONVERT(,,110):

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test202.js:20:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  2) Test 212: CONVERT dates with style 2. CONVERT DATE TO STRING:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test212.js:72:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  3) Test 212: CONVERT dates with style 3. CONVERT JAVASCRIPT DATE TO STRING:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test212.js:80:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  4) Test 212: CONVERT dates with style 4. CONVERT JAVASCRIPT DATE TO STRING:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test212.js:87:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  5) Test 212: CONVERT dates with style 5. CONVERT DATE TO STRING FROM TABLE:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test212.js:99:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  6) Test 212: CONVERT dates with style 6. CONVERT DATE TO STRING FROM TABLE:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test212.js:112:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  7) Test 212: CONVERT dates with style 7. CONVERT DATE TO STRING FROM TABLE:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test212.js:125:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  8) Test 212: CONVERT dates with style 8. CONVERT DATE TO STRING FROM TABLE without columns:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test212.js:138:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  9) Test 212: CONVERT dates with style 9. CONVERT DATE TO STRING FROM TABLE without columns:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test212.js:151:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  10) Test 232 Errors handling 3. Log error async:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test232.js:29:13)
     at alasql.exec (C:\Users\mrw\git\alasql\dist\alasql.js:4057:5)
     at alasql (C:\Users\mrw\git\alasql\dist\alasql.js:120:4)
     at Anonymous function (C:\Users\mrw\git\alasql\test\test232.js:28:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  11) Test 232 Errors handling 4. Log error sync:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test232.js:37:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  12) Test 238 Test from string and into string 1. JSON:
     Error: ENOENT: no such file or directory, open 'C:\Usersmrwgitalasql       est\test238.json'
     at fs.openSync (fs.js:584:3)
     at fs.writeFileSync (fs.js:1238:3)
     at utils.saveFile (C:\Users\mrw\git\alasql\dist\alasql.js:3397:13)
     at alasql.into.JSON (C:\Users\mrw\git\alasql\dist\alasql.js:13677:2)
     at Function code (Function code:1:7)
     at queryfn3 (C:\Users\mrw\git\alasql\dist\alasql.js:6035:3)
     at queryfn (C:\Users\mrw\git\alasql\dist\alasql.js:5767:3)
     at statement (C:\Users\mrw\git\alasql\dist\alasql.js:6751:3)
     at alasql.dexec (C:\Users\mrw\git\alasql\dist\alasql.js:4110:4)
     at alasql.exec (C:\Users\mrw\git\alasql\dist\alasql.js:4061:3)
     at alasql (C:\Users\mrw\git\alasql\dist\alasql.js:120:4)
     at Anonymous function (C:\Users\mrw\git\alasql\test\test238.js:15:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  13) Test 238 Test from string and into string 2. CSV() and AS:
     Error: ENOENT: no such file or directory, open 'C:\Usersmrwgitalasql       est\restest238a.csv'
     at fs.openSync (fs.js:584:3)
     at fs.writeFileSync (fs.js:1238:3)
     at utils.saveFile (C:\Users\mrw\git\alasql\dist\alasql.js:3397:13)
     at alasql.into.CSV (C:\Users\mrw\git\alasql\dist\alasql.js:13750:2)
     at Function code (Function code:1:7)
     at queryfn3 (C:\Users\mrw\git\alasql\dist\alasql.js:6035:3)
     at queryfn (C:\Users\mrw\git\alasql\dist\alasql.js:5767:3)
     at statement (C:\Users\mrw\git\alasql\dist\alasql.js:6751:3)
     at alasql.dexec (C:\Users\mrw\git\alasql\dist\alasql.js:4110:4)
     at alasql.exec (C:\Users\mrw\git\alasql\dist\alasql.js:4061:3)
     at alasql (C:\Users\mrw\git\alasql\dist\alasql.js:120:4)
     at Anonymous function (C:\Users\mrw\git\alasql\test\test238.js:23:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  14) Test 238 Test from string and into string 3. XLSX:
     Error: ENOENT: no such file or directory, open 'C:\Usersmrwgitalasql       est\restest238b.xlsx'
     at fs.openSync (fs.js:584:3)
     at fs.writeFileSync (fs.js:1238:3)
     at write_zip_type (C:\Users\mrw\git\alasql\node_modules\xlsx\xlsx.js:11412:16)
     at writeSync (C:\Users\mrw\git\alasql\node_modules\xlsx\xlsx.js:11421:12)
     at writeFileSync (C:\Users\mrw\git\alasql\node_modules\xlsx\xlsx.js:11436:2)
     at saveWorkbook (C:\Users\mrw\git\alasql\dist\alasql.js:14565:5)
     at doExport (C:\Users\mrw\git\alasql\dist\alasql.js:14474:3)
     at alasql.into.XLSX (C:\Users\mrw\git\alasql\dist\alasql.js:14447:3)
     at Function code (Function code:1:7)
     at queryfn3 (C:\Users\mrw\git\alasql\dist\alasql.js:6035:3)
     at queryfn (C:\Users\mrw\git\alasql\dist\alasql.js:5767:3)
     at statement (C:\Users\mrw\git\alasql\dist\alasql.js:6751:3)
     at alasql.dexec (C:\Users\mrw\git\alasql\dist\alasql.js:4110:4)
     at alasql.exec (C:\Users\mrw\git\alasql\dist\alasql.js:4061:3)
     at alasql (C:\Users\mrw\git\alasql\dist\alasql.js:120:4)
     at Anonymous function (C:\Users\mrw\git\alasql\test\test238.js:31:9)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  15) Test 242 Multi-columns Excel file 1. Read multi-column file:
     Uncaught Error: ENOENT: no such file or directory, open 'C:\Usersmrwgitalasql      est\test242.xlsx'
     at Anonymous function (C:\Users\mrw\git\alasql\dist\alasql.js:3280:21)
     at readFileAfterOpen (fs.js:324:5)

  16) Test 242 Multi-columns Excel file 2. Read multi-column file:
     Uncaught Error: ENOENT: no such file or directory, open 'C:\Usersmrwgitalasql      est\test242.xlsx'
     at Anonymous function (C:\Users\mrw\git\alasql\dist\alasql.js:3280:21)
     at readFileAfterOpen (fs.js:324:5)

  17) Test 392 Observable (issue #499) 2. Prepare test data:
     TypeError: Object doesn't support property or method 'observe'
     at Anonymous function (C:\Users\mrw\git\alasql\test\test392.js:27:5)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  18) Test 400 Trigger with INSERTED 3. Insert:

      AssertionError: [ [ 100, undefined ], [ 200, undefined ] ] deepEqual [ [ 100, 2016 ], [ 200, 2016 ] ]
      + expected - actual

       [
         [
           100
      -    [undefined]
      +    2016
         ]
         [
           200
      -    [undefined]
      +    2016
         ]
       ]

     at Anonymous function (C:\Users\mrw\git\alasql\test\test400.js:31:5)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  19) Test 408 - DATEADD() and DATEDIFF() 3. DATEDIFF():
     AssertionError: undefined deepEqual -1
     at Anonymous function (C:\Users\mrw\git\alasql\test\test408.js:43:5)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)

  20) Test 408 - DATEADD() and DATEDIFF() 4. DATE_ADD() MySQL-style:

      AssertionError: false == true
      + expected - actual

      -false
      +true

     at Anonymous function (C:\Users\mrw\git\alasql\test\test408.js:83:5)
     at callFnAsync (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:306:5)
     at Runnable.prototype.run (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:261:7)
     at Runner.prototype.runTest (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:421:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:528:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:341:7)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:351:7)
     at next (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:285:5)
     at Anonymous function (C:\Users\mrw\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:319:5)
```

**Comment by agershun** [comment]
Not bad. Will work on it! We also still have some FF incompatibilities (with date conversion)

**Comment by mathiasrw** [comment]
i feel the firefox things are more important at this moment

**Comment by agershun** [comment]
Agree

**Comment by mathiasrw** [comment]
Closed as its put on The Long List - only to be reopend when its time has come.
