### ISSUE TITLE
Version 0.2.3

### ISSUE THREAD

**Issue by agershun** [agershun/alasql#573]
@mathiasrw January is over. We have many changes and fixed issues. Let's release!

**Comment by agershun** [comment]
What is the next name? :)

**Comment by mathiasrw** [comment]
For sure it will be "Spetses" :) https://github.com/agershun/alasql/issues/533#issuecomment-172294390

Have you found a solution for getting it to the athmospherejs thing (Meteor)?

**Comment by mathiasrw** [comment]
Ohhh - I get your question - its the 2.4 you ask for. 

Let it be "Exogi" - where I first felt a true Greek dance circle at the town celebration :)

**Comment by mathiasrw** [comment]
Hmm. Getting errors on debian for test 429 and 430. I have to sort this out before releasing...

**Comment by mathiasrw** [comment]
Hmmmm - First time the test is running its ok, but next time we get 

```
  1) Test 429 Localstorage DELETE with WHERE clause:

      AssertionError: [ { str: undefined },
  { str: undefined },
  { str: undefined },
  { str: undefined },
  { str: undefined },
  { str: undefined deepEqual [ { str: 'b' } ]
      + expected - actual

       [
         {
      -    "str": [undefined]
      -  }
      -  {
      -    "str": [undefined]
      -  }
      -  {
      -    "str": [undefined]
      -  }
      -  {
      -    "str": [undefined]
      -  }
      -  {
      -    "str": [undefined]
      -  }
      -  {
      -    "str": [undefined]
      -  }
      -  {
           "str": "b"
         }
       ]
      
      at Context.<anonymous> (test429.js:23:10)

  2) Test 430 UNIQUE keyword in localStorage "before all" hook:
     Error: localStorage: Cannot create new database "test430g1" because it already exists
      at Function.LS.createDatabase (/Users/mrw/alasql/dist/alasql.js:16107:10)
      at yy.CreateDatabase.execute (/Users/mrw/alasql/dist/alasql.js:12856:43)
      at Function.alasql.drun (/Users/mrw/alasql/dist/alasql.js:4197:45)
      at Function.alasql.dexec (/Users/mrw/alasql/dist/alasql.js:4174:18)
      at Function.alasql.exec (/Users/mrw/alasql/dist/alasql.js:4111:17)
      at alasql (/Users/mrw/alasql/dist/alasql.js:120:18)
      at Context.<anonymous> (test430.js:13:5)

  3) Test 430 UNIQUE keyword in localStorage "after all" hook:
     TypeError: Cannot read property 'engineid' of undefined
      at yy.DetachDatabase.execute (/Users/mrw/alasql/dist/alasql.js:12905:39)
      at Function.alasql.dexec (/Users/mrw/alasql/dist/alasql.js:4166:45)
      at Function.alasql.exec (/Users/mrw/alasql/dist/alasql.js:4111:17)
      at alasql (/Users/mrw/alasql/dist/alasql.js:120:18)
      at Context.<anonymous> (test430.js:18:4)

```

Still looking into it...

**Comment by mathiasrw** [comment]
[Resetting](https://github.com/agershun/alasql/commit/2ffb642deb527bbd4ed511244517886746231bff) the [test429.json](https://github.com/agershun/alasql/blob/develop/test/test429.json) will [remove the errors](https://travis-ci.org/agershun/alasql/jobs/106425477). 

So I have to find out what the idea behind 
https://github.com/agershun/alasql/blob/88e5c43207c5ad7940b3ad1438e6aded2e33d934/test/test429.js#L5 is.

I have `.skip`ed the test 429 and 430
