### ISSUE TITLE
Meteor 1.3.2.4: __dirname not defined

### ISSUE THREAD

**Issue by diegonc** [agershun/alasql#687]
Hello

I'm trying to use this package in latest Meteor version but it's complaining that `__dirname` is not defined.

```
$ meteor --version
Meteor 1.3.2.4
$ meteor create test-alasql
$ cd test-alasql
$ meteor add agershun:alasql
...
agershun:alasql  added, version 0.2.7    
...
$ meteor
[[[[[ ~/develop/scratchpad/test-alasql ]]]]]  

=> Started proxy.                             
=> Started MongoDB.                           
W20160531-14:43:12.808(-3)? (STDERR)          
W20160531-14:43:12.809(-3)? (STDERR) /home/diego/.meteor/packages/meteor-tool/.1.3.2_4.1xio9ot++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160531-14:43:12.810(-3)? (STDERR) 						throw(ex);
W20160531-14:43:12.810(-3)? (STDERR) 						      ^
W20160531-14:43:12.810(-3)? (STDERR) ReferenceError: __dirname is not defined
W20160531-14:43:12.810(-3)? (STDERR)     at Object.x.findAlaSQLPath (packages/agershun_alasql/dist/alasql.min.js:9:1)
W20160531-14:43:12.810(-3)? (STDERR)     at undefined.location.reload.undefined.process.browser.function.require.function.require.specified.alasql.worker.e (packages/agershun_alasql/dist/alasql.min.js:9:1)
W20160531-14:43:12.810(-3)? (STDERR)     at packages/agershun_alasql/dist/alasql.min.js:2:1
W20160531-14:43:12.810(-3)? (STDERR)     at Package (packages/agershun_alasql/dist/alasql.min.js:2:1)
W20160531-14:43:12.811(-3)? (STDERR)     at /home/diego/develop/scratchpad/test-alasql/.meteor/local/build/programs/server/packages/agershun_alasql.js:35:4
W20160531-14:43:12.811(-3)? (STDERR)     at /home/diego/develop/scratchpad/test-alasql/.meteor/local/build/programs/server/packages/agershun_alasql.js:42:3
W20160531-14:43:12.811(-3)? (STDERR)     at /home/diego/develop/scratchpad/test-alasql/.meteor/local/build/programs/server/boot.js:283:10
W20160531-14:43:12.811(-3)? (STDERR)     at Array.forEach (native)
W20160531-14:43:12.811(-3)? (STDERR)     at Function._.each._.forEach (/home/diego/.meteor/packages/meteor-tool/.1.3.2_4.1xio9ot++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160531-14:43:12.811(-3)? (STDERR)     at /home/diego/develop/scratchpad/test-alasql/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```

Is anyone having the same issue?

**Comment by mathiasrw** [comment]
Hi @diegonc 

Thank you so much for taking the time to let us know. Is it at the client or the server you are getting this?

**Comment by diegonc** [comment]
I think it's the server. It doesn't get to the point where Meteor starts listening so I didn't try to open the webpage nor add code to actually use the package.

Apparently, it's some issue at the bootstrapping stage.

**Comment by mathiasrw** [comment]
Im able to replicate it now. Thank you for good instructions in your initial comment. 

I must fix this as soon as possible!

**Comment by mathiasrw** [comment]
Aww... looks like 1.3 performs static analysis on the packages - so all references to require and __dirname that will only be invoked if its running in node is blocking. 

We have to do what was suggested in https://github.com/agershun/alasql/issues/676 and make a build targeted browsers only.

**Comment by diegonc** [comment]
Thanks for fixing it. It's working. :)

BTW, what do you mean by blocking (when describing the static analysis Meteor does)?

**Comment by mathiasrw** [comment]
> what do you mean by blocking

The static analysis was not passing so Meteor would never executing the code - so it "blocked" the execusion of the code.
