### ISSUE TITLE
TypeError: Cannot read property 'undefined' of undefined

### ISSUE THREAD

**Issue by Eivlys** [agershun/alasql#792]
I'm using alasql with AngularJs , and include it in the comment way before requireJS:
`<script src="vendor/alasql/alasql.min.js" ></script>
<script src="vendor/alasql/xlsx.core.min.js"></script>`

but i got an error in the console:
TypeError: Cannot read property 'undefined' of undefined
    at eval [as intoallfn] (eval at <anonymous> (http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:11:15782), <anonymous>:3:48)
    at c (http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:2:10846)
    at u (http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:2:7524)
    at Object.eval [as datafn] (eval at <anonymous> (http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:11:19335), <anonymous>:3:57)
    at http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:2:7052
    at Array.forEach (native)
    at o (http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:2:7012)
    at a (http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:11:15885)
    at Function.y.dexec (http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:10:23955)
    at Function.y.exec (http://cdn.jsdelivr.net/alasql/0.3/alasql.min.js:10:23392)

what can i do to fix this?

**Comment by mathiasrw** [comment]
Are you running any code to get the error?

**Comment by Eivlys** [comment]
I'm running 
`alasql('SELECT * INTO XLSX("current.xlsx",{headers:true}) FROM ?',[$scope.exportList]);`

$scope.exportList is the data i got from node server

**Comment by mathiasrw** [comment]
What format is the data from the node server?

**Comment by Eivlys** [comment]
the data is an object [ object, object, object ] ,like:
`[
  {
    name:'A',
    id: 1
  },
  {
    name: 'B',
    id: 2
  },
  {
     name: 'C',
     id: 3
  }
]`

**Comment by mathiasrw** [comment]
What do you get if you do a
```js
alasql('SELECT * INTO XLSX("current.xlsx",{headers:true}) FROM ?',[[ { name:'A', id: 1 }, { name: 'B', id: 2 }, { name: 'C', id: 3 } ]]);
```

?

**Comment by Eivlys** [comment]
well if use`[ { name:'A', id: 1 }, { name: 'B', id: 2 }, { name: 'C', id: 3 } ]` ,I can get the excel correctly.
so there is something wrong with the data i got, what form it should be?

**Comment by mathiasrw** [comment]
I dont know what to say. if `$scope.exportList` is truely in the format of `[ { name:'A', id: 1 }, { name: 'B', id: 2 }, { name: 'C', id: 3 } ]` it does not make sense that its not working?

**Comment by bkwdesign** [comment]
I am having the same issue nearly. 
This [dead simple JSFiddle](http://jsfiddle.net/sujit77/9d6yrom9/69/) works for me just fine, and is how I discovered this library

When I use the exact CDN scripts and paste in the exact contents of the fiddle (except I've moved the function out of the "window" object and attached it to my Knockout.js page model object, the error is what I get

**Comment by mathiasrw** [comment]
Have you guys had a look at https://github.com/agershun/alasql/wiki/Angular.js ?
