### ISSUE TITLE
 React: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by webpansy** [agershun/alasql#809]
When I use alasql in a react javascript file, I import it as below:
```
import alasql from 'alasql';
```
The webpack occurs me these error code:
```
WARNING in ./~/alasql/dist/alasql.fs.js
Critical dependencies:
3359:70-77 require function is used in a way in which dependencies cannot be statically extracted
 @ ./~/alasql/dist/alasql.fs.js 3359:70-77

WARNING in ./~/alasql/dist/alasql.fs.js
Module not found: Error: Cannot resolve module 'vertx' in E:\Workspace\mock-server\node_modules\alasql\dist
 @ ./~/alasql/dist/alasql.fs.js 4680:667-677

WARNING in ./~/alasql/dist/alasql.d.ts
Module parse failed: E:\Workspace\mock-server\node_modules\alasql\dist\alasql.d.ts Unexpected token (6:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (6:8)
    at Parser.pp$4.raise (E:\Workspace\mock-server\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp.unexpected (E:\Workspace\mock-server\node_modules\acorn\dist\acorn.js:603:10)
    at Parser.pp.semicolon (E:\Workspace\mock-server\node_modules\acorn\dist\acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (E:\Workspace\mock-server\node_modules\acorn\dist\acorn.js:966:10)
    at Parser.pp$1.parseStatement (E:\Workspace\mock-server\node_modules\acorn\dist\acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (E:\Workspace\mock-server\node_modules\acorn\dist\acorn.js:638:25)
    at Parser.parse (E:\Workspace\mock-server\node_modules\acorn\dist\acorn.js:516:17)
    at Object.parse (E:\Workspace\mock-server\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (E:\Workspace\mock-server\node_modules\webpack\lib\Parser.js:902:15)
    at DependenciesBlock.<anonymous> (E:\Workspace\mock-server\node_modules\webpack\lib\NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (E:\Workspace\mock-server\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (E:\Workspace\mock-server\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at E:\Workspace\mock-server\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (E:\Workspace\mock-server\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at E:\Workspace\mock-server\node_modules\graceful-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
 @ ./~/alasql/dist ^\.\/.*$
```

I have no idea that it caused by my incorrect use or a bug? Inspire me please, thank you!

**Comment by mathiasrw** [comment]
I see. 

The thig is that we support the "SQL" syntax `REQUIRE myPlugin.js` and the implementation is made with 

```js
{ $$ = new yy.Require({paths:$2}); }
```

do your now if you can put at comment in the source so react gets a little less cranky?

**Comment by nickdeis** [comment]
That isn't a React issue, it's a webpack one. @mathiasrw , I have added some additional detail to the webpack guide for alasql in a pull request. You can now load alasql with webpack in three ways, all of which depend on your needs. I personally will vouch for noParse, since it will increase the performance of your webpack build.

**Comment by mathiasrw** [comment]
Thank you @nickdeis for sharing - it means a lot (to me) that others add info when they have it :)
