### ISSUE TITLE
db.compile is not a function

### ISSUE THREAD

**Issue by onderaltintas** [agershun/alasql#814]
From [getting started](https://github.com/agershun/alasql/wiki/Getting%20started) page on the wiki I was trying to insert into table but db.compile is not a function.

Code:
```
var db = new alasql.Database();
db.exec('CREATE TABLE people (age INT)');
var insert1 = db.compile('INSERT INTO people (?)'); 
```
Here I get the following error:
```
TypeError: db.compile is not a function
    at repl:1:18
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
    at REPLServer.Interface._onLine (readline.js:210:10)
    at REPLServer.Interface._line (readline.js:549:8)
    at REPLServer.Interface._ttyWrite (readline.js:826:14)
```
If I try:
`db.exec('INSERT INTO people (?)',[5]);`
I get:
```
Expecting 'LITERAL', 'BRALITERAL', got 'QUESTION'
    at Object.parser.parseError (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:2198:8)
    at Object.parse (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:2072:22)
    at Function.alasql.parse (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:4325:22)
    at Function.alasql.dexec (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:4509:19)
    at Database.exec (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:4832:16)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
```
If I try:
`db.exec('INSERT INTO people (5)',[]);`
I get the following error:
```
Error: Parsing halted while starting to recover from another error.
    at Object.parse (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:2087:27)
    at Function.alasql.parse (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:4325:22)
    at Function.alasql.dexec (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:4509:19)
    at Database.exec (C:\alasqltest\node_modules\alasql\dist\alasql.fs.js:4832:16)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
```

**Comment by mathiasrw** [comment]
For the compile, please use the original `alasql`object as shown in https://github.com/agershun/alasql/wiki/Compile

Can you try to do a `db.exec('INSERT INTO people value (5)');`and see if that works? If not, please provide a jsfiddle demonstrating the SQL you use to create the `people`table
