### ISSUE TITLE
3.8 Update Bug?

### ISSUE THREAD

**Issue by bbrearle** [agershun/alasql#849]
Quering an external csv resource appears to have stopped working (atleast in this use case) on the update from 3.6 to 3.8.

I have a back up copy of the 3.6 version. It is working here: [fiddle](https://jsfiddle.net/bbrearle/m905s2xx/).

And 3.8 not working here: [fiddle](https://jsfiddle.net/bbrearle/2udw63qp/).

Console Error:

`Uncaught TypeError: Cannot read property 'autoExt' of null
    at Object.C.autoExtFilename (https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:11:9316)
    at Object.A.from.CSV (https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:15:22714)
    at Object.eval [as datafn] (eval at <anonymous> (https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:1:1), <anonymous>:3:27)
    at https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:2:6976
    at Array.forEach (native)
    at o (https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:2:6936)
    at s (https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:12:8299)
    at Function.A.dexec (https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:11:16432)
    at Function.A.exec (https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:11:15867)
    at A (https://cdnjs.cloudflare.com/ajax/libs/alasql/0.3.8/alasql.min.js:2:20273)`

I think it has to do with the auto-extension, in this case .csv, being appended to the end of the csv location directory. In this case a call with query string (api key).

Any way to disable auto extension? Thanks.

**Comment by mathiasrw** [comment]
Woops!

Please use version 0.3.9 - just released...

**Comment by bbrearle** [comment]
Awesome. Thanks.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
