### ISSUE TITLE
alasql insert into excel issue

### ISSUE THREAD

**Issue by siddisking** [agershun/alasql#866]
I Have created an excel sheet and just want to insert into it and select from it.

I am successful in getting all the elements in the form of objects but I cannot insert into it here is my code.

```
var obj;
        alasql.promise('select * from xlsx("MyAwesomeData.xlsx") ')
            .then(function(data){
                obj=data;
                 console.log(data);
            });
            var data1 = [{a:199,b:1980},{a:299,b:290}];
            alasql.promise(' INSERT INTO XLSX("MyAwesomeData.xlsx") values?',{sheetid:'Good',header:true},[data1])
            .then(function(data){
                 console.log('Data saved');
            }).catch(function(err){
                 console.log('Error:', err);
            });
```

The error is as follows:-
```

Error: n {message: "Parse error on line 1:↵ INSERT INTO XLSX("MyAwesom…^↵Expecting 'LITERAL', 'BRALITERAL', got 'STRING'", hash: Object}hash: Objectmessage: "Parse error on line 1:↵ INSERT INTO XLSX("MyAwesomeData.xlsx"↵------------------^↵Expecting 'LITERAL', 'BRALITERAL', got 'STRING'"__proto__: Error
    at e.parseError (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:8:30251)
    at e.parse (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:8:31416)
    at Function.w.parse (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:9:24727)
    at Function.w.dexec (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:9:26065)
    at Function.w.exec (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:9:25814)
    at w (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:20260)
    at file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:10:1928
    at Promise (<anonymous>)
    at H (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:10:1893)
    at Function.w.promise (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:10:2436)
```

**Comment by mathiasrw** [comment]
Have a look at https://github.com/agershun/alasql/wiki/XLSX#save-data-to-xlsx to see a working example. 

(hint: your code is lacking a `select *` part)

Please reopen the issue if this does not help with your problem...

**Comment by siddisking** [comment]
Thanks for the hints.

I commented out the read promise also changed the query to this.
```
var data1 = {a:199,b:1980};
	   //alasql.promise('SELECT * INTO XLSX("MyAwesomeData.xlsx") VALUES ?',[data1])
	   alasql.promise('SELECT * INTO XLSX("MyAwesomeData.xlsx") FROM ?',{sheetid:"Good"},{header:"true"},[data1])
            .then(function(data){
                 console.log('Data saved');
            }).catch(function(err){
                 console.log('Error:', err);
            });
		
```

Now the error is something like this.

```
Error: Error: Data source number 0 in undefined
    at d (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:12085)
    at c (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:7607)
    at u (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:7522)
    at Object.eval [as datafn] (eval at <anonymous> (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:10:21665), <anonymous>:3:57)
    at file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:7053
    at Array.forEach (native)
    at o (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:7013)
    at a (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:10:18215)
    at Function.w.dexec (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:9:26377)
    at Function.w.exec (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:9:25814)
```

**Comment by mathiasrw** [comment]
All the parameters needs to be in one array, so put `[...]` around `{sheetid:"Good"},{header:"true"},[data1]`
