### ISSUE TITLE
Not able to insert into excel files

### ISSUE THREAD

**Issue by siddisking** [agershun/alasql#869]
Hi I am trying to insert data into my excel sheet. 
The excel file already exists I just want to add this row.
Below is the code that I am using
```
var data1 = {a:199,b:1980};
	   alasql.promise('SELECT * INTO XLSX("MyAwesomeData.xlsx") FROM ?',{sheetid:"Good"},{header:"true"},[data1])
            .then(function(data){
                 console.log('Data saved');
            }).catch(function(err){
                 console.log('Error:', err);
            });
```

I am getting this error 

```
Error: Error: Data source number 0 in undefined
    at d (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:12085)
    at c (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:7607)
    at u (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:7522)
    at Object.eval [as datafn] (eval at <anonymous> (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:10:21665), <anonymous>:3:57)
    at file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:7053
    at Array.forEach (native)
    at o (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:2:7013)
    at a (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:10:18215)
    at Function.w.dexec (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:9:26377)
    at Function.w.exec (file:///C:/Users/Siddhant/Desktop/Slider/alasql.min.js:9:25814)

```
**Please don't close the issue until its resolved.**   
-Thanks

**Comment by mathiasrw** [comment]
The error is comming because `{sheetid:"Good"},{header:"true"},[data1]`must be in an array (encapsulate with `[...]` to fix|)

THe library can not add to an existing file. Only export as new file...
