### ISSUE TITLE
Asynch fail of create FILESTORAGE 

### ISSUE THREAD

**Issue by peterprib** [agershun/alasql#980]
alasql('CREATE FILESTORAGE DATABASE system("./systemDB.json")')

This fails async some time later causing total script failure and not possible to try/catch

Error: Cannot create new database file, because it alreagy exists
    at C:\Users\db2admin\git\nodaldbms\node_modules\alasql\dist\alasql.fs.js:19159:11
    at FSReqWrap.cb [as oncomplete] (fs.js:257:19)

**Comment by mathiasrw** [comment]
Hi Peter. Its awesome that you find all these problems and make issues about them. 

Fixed the spelling error at first!

All interaction with the filesystem in async. No try catch would work. Have you tried `catch` with a promise notation?

```
alasql(['CREATE FILESTORAGE DATABASE system("./systemDB.json")'])
.then(res=≥{console.log(res)})
.catch(e=>{console.log('something went wrong', e)})
```
 
I cant test run this myself at this moment, so sorry if this is not working.

**Comment by peterprib** [comment]
yes

my the was alasql.exec(['create ...']) does not work as it doesn't accept
an array.  Promise works

Regards

Peter Prib

On 25 February 2018 at 21:18, Mathias Rangel Wulff <notifications@github.com

**Comment by mathiasrw** [comment]
No, `alasql.exec` will for sure not work as it does not support the shorthand promise notation. 


Try ```alasql(['create ...```

**Comment by renjiza** [comment]
when i run this code 

alasql(['CREATE FILESTORAGE DATABASE system("./systemDB.json")'])
.then(res=≥{console.log(res)})
.catch(e=>{console.log('something went wrong', e)})

i've got some problem like 

something went wrong Error: You can use exists() only in Node.js or Apach Cordova
    at Object.C.fileExists (alasql.js:11)
    at Function.pe.createDatabase (alasql.js:16)
    at K.CreateDatabase.execute (alasql.js:14)
    at Function.A.dexec (alasql.js:11)
    at Function.A.exec (alasql.js:11)
    at A (alasql.js:2)
    at alasql.js:11
    at new Promise (<anonymous>)
    at j (alasql.js:11)
    at H (alasql.js:11)

is fileStorage engine doesnt support for web browser like chrome ?

**Comment by renjiza** [comment]
because i got problem using alasql pure DB , when i refresh on my browser and i check my alasql DB is gone , anyone can help me ?

**Comment by mathiasrw** [comment]
Hi @renjiza - please see the comment I gave you in the other issue. 

And please: for the future create a new issue when your question is not directly related to the existing subject.
